from pyrogram import Client

# Your API credentials from my.telegram.org
API_ID = 123456  # replace with your API_ID (int)
API_HASH = "your_api_hash"  # replace with your API_HASH (str)

# Your userbot session string (generated by @SessionStringzBot)
STRING_SESSION = "BQB7RAsAM45JalThyilPvtY0GRI6YOFMQrVXkqtixaB3qgt6NAQeuE7UVD_dbm3KNval_3QI2CoKnJO4k8UzUZRTlMlKcHfaOMAnY5wlpyedK8kQuJmzCnrEajU1hPv_8SmLS68suXN54NmB19g299CNwIE36a7fsa338NQbz65YiN9rFFnZAmeqbBSb0q2la2Y8XSwTQwzZmB8aE4IuMeZ_9LYqxN3eE3jqm5GUIQFy4QgvkMH_962zYJ3MPD_v5b-tIhm-Pge4ysjvGZf2Sp26wM_gVpFieapmFfe6elT0e8IV-ZN4C2eODRXSvXQcP92qWIomXreMxgKcV8Pc6CcFmjWF-AAAAAB2BX6FAA"

app = Client(
    session_name=STRING_SESSION,
    api_id=API_ID,
    api_hash=API_HASH
)

with app:
    print("Userbot started!")
    # You can now call any Pyrogram user methods here
    # For example, get your own user info:
    me = app.get_me()
    print(f"Logged in as: {me.first_name} (@{me.username})")
