services:
  - type: web
    name: save-restricted-bot
    runtime: python
    repo: https://github.com/mr-adnan-adu/Save-Any-Restricted-robot
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
